//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtoparkSis.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DbOtoparkEntities : DbContext
    {
        public DbOtoparkEntities()
            : base("name=DbOtoparkEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_Alanlar> tbl_Alanlar { get; set; }
        public virtual DbSet<Tbl_Arac> Tbl_Arac { get; set; }
        public virtual DbSet<Tbl_Park> Tbl_Park { get; set; }
        public virtual DbSet<Tbl_Musteri> Tbl_Musteri { get; set; }
        public virtual DbSet<Tbl_Personel> Tbl_Personel { get; set; }
        public virtual DbSet<Tbl_Yonetici> Tbl_Yonetici { get; set; }
    
        public virtual ObjectResult<Nullable<int>> BUGUNİSLEM()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("BUGUNİSLEM");
        }
    
        public virtual ObjectResult<string> ENAKTİFUYE()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("ENAKTİFUYE");
        }
    
        public virtual ObjectResult<string> ENBASARİLİPER()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("ENBASARİLİPER");
        }
    
        public virtual ObjectResult<string> UYEARACSAYİSİ()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("UYEARACSAYİSİ");
        }
    }
}
