//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtoparkSis.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Park
    {
        public int Id { get; set; }
        public Nullable<int> Musteri { get; set; }
        public Nullable<int> Personel { get; set; }
        public Nullable<int> Arac { get; set; }
        public Nullable<int> Konumu { get; set; }
        public Nullable<System.DateTime> GirisTarihi { get; set; }
        public Nullable<System.DateTime> ÇikisTarihi { get; set; }
        public Nullable<int> Fiyat { get; set; }
        public Nullable<bool> Durum { get; set; }
    
        public virtual tbl_Alanlar tbl_Alanlar { get; set; }
        public virtual Tbl_Arac Tbl_Arac { get; set; }
        public virtual Tbl_Musteri Tbl_Musteri { get; set; }
        public virtual Tbl_Personel Tbl_Personel { get; set; }
    }
}
