//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtoparkSis.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Arac
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Arac()
        {
            this.Tbl_Park = new HashSet<Tbl_Park>();
        }
    
        public int Id { get; set; }
        public Nullable<int> AraçSahibi { get; set; }
        public string Plaka { get; set; }
        public Nullable<bool> Durum { get; set; }
        public Nullable<bool> Durum2 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Park> Tbl_Park { get; set; }
        public virtual Tbl_Musteri Tbl_Musteri { get; set; }
    }
}
